### PR TITLE
fix: update Exoscale DNS script

### LINKED ISSUE #5165: DNS API for Exoscale Deprecated
The DNS API mode for Exoscale does not work anymore, as by 1st May 2024 they deprecated their v1 of their API (ref: [Deprecation Notice](https://changelog.exoscale.com/en/deprecation-api-v1-as-of-may-1st-2024-uVYHUVZ3))

Error log
-----------------
```
# acme.sh --renew-all
[Mon Jun  3 11:33:06 AM CEST 2024] Renew: 'XXX'
[Mon Jun  3 11:33:07 AM CEST 2024] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Jun  3 11:33:07 AM CEST 2024] Single domain='XXX'
[Mon Jun  3 11:33:07 AM CEST 2024] Getting domain auth token for each domain
[Mon Jun  3 11:33:09 AM CEST 2024] Getting webroot for domain='XXX'
[Mon Jun  3 11:33:09 AM CEST 2024] Adding txt value: XXX for domain:  _acme-challenge.XXX
[Mon Jun  3 11:33:09 AM CEST 2024] invalid domain
[Mon Jun  3 11:33:09 AM CEST 2024] Error add txt for domain:_acme-challenge.XXX
[Mon Jun  3 11:33:09 AM CEST 2024] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Mon Jun  3 11:33:10 AM CEST 2024] Error renew XXX.
```

Additional information
-----------------
In dnsapi/dns_exoscale.sh the API is set to `EXOSCALE_API=https://api.exoscale.com/dns/v1`, which by now is deprecated. Needs to be updated to v2 (ref: [V2 API Doc](https://openapi-v2.exoscale.com/)). However, I haven't checked if only changing the endpoint is sufficient or whether the API itself also changed.

### PR DESCRIPTION
**Pull request by imiric**
This updates the Exoscale DNS script to work with v2 of their API.

I ran the DNS CI workflow in my fork according to [the DNS API Dev Guide](https://github.com/acmesh-official/acme.sh/wiki/DNS-API-Dev-Guide), and [it passed](https://github.com/imiric/acme.sh/actions/runs/20057416510).

The script is very brittle due to parsing JSON with `_egrep_o`, so any improvement suggestions would be appreciated.

Closes #5165

### CODE REVIEW

File: dnsapi/dns_exoscale.sh [hunk 1]
```diff
@@ -8,169 +8,199 @@ Options:
...
+  records=$(_exoscale_rest GET "/dns-domain/$root_id/record")
+
+  # Convert search name to lowercase for case-insensitive matching
+  name_lower=$(echo "$name" | tr '[:upper:]' '[:lower:]')
+
+  echo "$records" | _egrep_o '\{[^}]*"name":"[^"]*"[^}]*\}' | while read -r record; do
+    record_name=$(echo "$record" | _egrep_o '"name":"[^"]*"' | cut -d'"' -f4)
+    record_name_lower=$(echo "$record_name" | tr '[:upper:]' '[:lower:]')
+    if [ "$record_name_lower" = "$name_lower" ]; then
+      echo "$record" | _egrep_o '"id":"[^"]*"' | head -n1 | cut -d'"' -f4
```
Comment (neilpang) [inline dnsapi/dns_exoscale.sh]: use  `_head_n()` function

File: dnsapi/dns_exoscale.sh [hunk 2]
```diff
@@ -8,169 +8,199 @@ Options:
...
+  expiration=$(_math "$(date +%s)" + 300)  # 5m from now
 
-  if [ "$token" ]; then
-    export _H2="X-DNS-Domain-Token: $token"
-  else
-    export _H2="X-DNS-Token: $EXOSCALE_API_KEY:$EXOSCALE_SECRET_KEY"
-  fi
+  # Build the message with the actual body or empty line
+  message=$(printf "%s %s\n%s\n\n\n%s" "$method" "/v2$path" "$data" "$expiration")
+  signature=$(printf "%s" "$message" | ${ACME_OPENSSL_BIN:-openssl} dgst -sha256 -hmac "$EXOSCALE_SECRET_KEY" -binary | _base64)
```
Comment (neilpang) [inline dnsapi/dns_exoscale.sh]: don't use openssl here, use  `_hmac()`

File: dnsapi/dns_exoscale.sh (hunk 1 above)
Comment (imiric) [reply dnsapi/dns_exoscale.sh]: Thanks, fixed in 1413aa33.

File: dnsapi/dns_exoscale.sh (hunk 2 above)
Comment (imiric) [reply dnsapi/dns_exoscale.sh]: Thanks, fixed in 1413aa33.

**Comment by imiric** [comment]
I addressed the suggestions, resolved the ShellCheck warnings, and rebased on latest `dev` in 1413aa33. [The DNS CI workflow passed.](https://github.com/imiric/acme.sh/actions/runs/20057416510)

Please take another look.
