### PR TITLE
fix #2031 dns_me id parse

### LINKED ISSUE #2031: Invalid Domain with DNS Made Easy DNS
**Steps to reproduce**
------------------

acme.sh --issue -d mydomain.com -d *.mydomain.com --dns dns_me --keylength ec-384 --debug 2

**Debug log**
-----------------
```
[Mon Jan 14 04:52:19 UTC 2019] Lets find script dir.
[Mon Jan 14 04:52:19 UTC 2019] _SCRIPT_='/root/.acme.sh/acme.sh'
[Mon Jan 14 04:52:19 UTC 2019] _script='/root/.acme.sh/acme.sh'
[Mon Jan 14 04:52:19 UTC 2019] _script_home='/root/.acme.sh'
[Mon Jan 14 04:52:19 UTC 2019] Using config home:/root/.acme.sh
[Mon Jan 14 04:52:19 UTC 2019] LE_WORKING_DIR='/root/.acme.sh'
https://github.com/Neilpang/acme.sh
v2.8.0
[Mon Jan 14 04:52:19 UTC 2019] _main_domain='mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] _alt_domains='*.mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] Using config home:/root/.acme.sh
[Mon Jan 14 04:52:19 UTC 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jan 14 04:52:19 UTC 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mon Jan 14 04:52:19 UTC 2019] DOMAIN_PATH='/root/.acme.sh/mydomain.com_ecc'
[Mon Jan 14 04:52:19 UTC 2019] 'dns_me' does not contain 'dns'
[Mon Jan 14 04:52:19 UTC 2019] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Mon Jan 14 04:52:19 UTC 2019] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Jan 14 04:52:19 UTC 2019] GET
[Mon Jan 14 04:52:19 UTC 2019] url='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jan 14 04:52:19 UTC 2019] timeout=
[Mon Jan 14 04:52:19 UTC 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.IVWf5Jofrg  -g '
[Mon Jan 14 04:52:19 UTC 2019] ret='0'
[Mon Jan 14 04:52:19 UTC 2019] response='{
  "EG9BnoWDURM": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}'
[Mon Jan 14 04:52:19 UTC 2019] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Mon Jan 14 04:52:19 UTC 2019] ACME_NEW_AUTHZ
[Mon Jan 14 04:52:19 UTC 2019] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Jan 14 04:52:19 UTC 2019] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mon Jan 14 04:52:19 UTC 2019] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Mon Jan 14 04:52:19 UTC 2019] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Mon Jan 14 04:52:19 UTC 2019] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Jan 14 04:52:19 UTC 2019] ACME_VERSION='2'
[Mon Jan 14 04:52:19 UTC 2019] _on_before_issue
[Mon Jan 14 04:52:19 UTC 2019] _chk_main_domain='mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] _chk_alt_domains='*.mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] 'dns_me' does not contain 'no'
[Mon Jan 14 04:52:19 UTC 2019] Le_LocalAddress
[Mon Jan 14 04:52:19 UTC 2019] d='mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] Check for domain='mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] _currentRoot='dns_me'
[Mon Jan 14 04:52:19 UTC 2019] d='*.mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] Check for domain='*.mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] _currentRoot='dns_me'
[Mon Jan 14 04:52:19 UTC 2019] d
[Mon Jan 14 04:52:19 UTC 2019] 'dns_me' does not contain 'apache'
[Mon Jan 14 04:52:19 UTC 2019] _saved_account_key_hash='/QbS8ZHZZDFU5padiLDCG5KofzPBJbYFsmFGQ0wcVCs='
[Mon Jan 14 04:52:19 UTC 2019] _saved_account_key_hash is not changed, skip register account.
[Mon Jan 14 04:52:19 UTC 2019] Read key length:
[Mon Jan 14 04:52:19 UTC 2019] Creating domain key
[Mon Jan 14 04:52:19 UTC 2019] Using config home:/root/.acme.sh
[Mon Jan 14 04:52:19 UTC 2019] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Jan 14 04:52:19 UTC 2019] _ACME_SERVER_HOST='acme-v02.api.letsencrypt.org'
[Mon Jan 14 04:52:19 UTC 2019] _createkey for file:/root/.acme.sh/mydomain.com_ecc/mydomain.com.key
[Mon Jan 14 04:52:19 UTC 2019] Use length 384
[Mon Jan 14 04:52:19 UTC 2019] Using ec name: secp384r1
[Mon Jan 14 04:52:19 UTC 2019] The domain key is here: /root/.acme.sh/mydomain.com_ecc/mydomain.com.key
[Mon Jan 14 04:52:19 UTC 2019] _createcsr
[Mon Jan 14 04:52:19 UTC 2019] domain='mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] domainlist='*.mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] csrkey='/root/.acme.sh/mydomain.com_ecc/mydomain.com.key'
[Mon Jan 14 04:52:19 UTC 2019] csr='/root/.acme.sh/mydomain.com_ecc/mydomain.com.csr'
[Mon Jan 14 04:52:19 UTC 2019] csrconf='/root/.acme.sh/mydomain.com_ecc/mydomain.com.csr.conf'
[Mon Jan 14 04:52:19 UTC 2019] _is_idn_d='*.mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] _idn_temp
[Mon Jan 14 04:52:19 UTC 2019] domainlist='*.mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] Multi domain='DNS:mydomain.com,DNS:*.mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] _is_idn_d='mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] _idn_temp
[Mon Jan 14 04:52:19 UTC 2019] _csr_cn='mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] Getting domain auth token for each domain
[Mon Jan 14 04:52:19 UTC 2019] d='*.mydomain.com'
[Mon Jan 14 04:52:19 UTC 2019] d
[Mon Jan 14 04:52:19 UTC 2019] _identifiers='{"type":"dns","value":"mydomain.com"},{"type":"dns","value":"*.mydomain.com"}'
[Mon Jan 14 04:52:19 UTC 2019] url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Jan 14 04:52:19 UTC 2019] payload='{"identifiers": [{"type":"dns","value":"mydomain.com"},{"type":"dns","value":"*.mydomain.com"}]}'
[Mon Jan 14 04:52:19 UTC 2019] RSA key
[Mon Jan 14 04:52:19 UTC 2019] Get nonce with HEAD. ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Jan 14 04:52:19 UTC 2019] HEAD
[Mon Jan 14 04:52:19 UTC 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Jan 14 04:52:19 UTC 2019] body
[Mon Jan 14 04:52:19 UTC 2019] _postContentType='application/jose+json'
[Mon Jan 14 04:52:19 UTC 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.kB7u49OI66  -g '
[Mon Jan 14 04:52:20 UTC 2019] _ret='0'
[Mon Jan 14 04:52:20 UTC 2019] _headers='HTTP/1.1 204 No Content
Server: nginx
Replay-Nonce: FgaASFxgTnC2AcviKjuG-ZBPIHKoP4Zb8fQ1KR5BNRo
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 14 Jan 2019 04:52:20 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 14 Jan 2019 04:52:20 GMT
Connection: keep-alive
'
[Mon Jan 14 04:52:20 UTC 2019] _CACHED_NONCE='FgaASFxgTnC2AcviKjuG-ZBPIHKoP4Zb8fQ1KR5BNRo'
[Mon Jan 14 04:52:20 UTC 2019] nonce='FgaASFxgTnC2AcviKjuG-ZBPIHKoP4Zb8fQ1KR5BNRo'
[Mon Jan 14 04:52:20 UTC 2019] POST
[Mon Jan 14 04:52:20 UTC 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Jan 14 04:52:20 UTC 2019] body='{"protected": "eyJub25jZSI6ICJGZ2FBU0Z4Z1RuQzJBY3ZpS2p1Ry1aQlBJSEtvUDRaYjhmUTFLUjVCTlJvIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIiLCAiYWxnIjogIlJTMjU2IiwgImtpZCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hY2N0LzQ3NDI0MDEwIn0", "payload": "eyJpZGVudGlmaWVycyI6IFt7InR5cGUiOiJkbnMiLCJ2YWx1ZSI6InByb2plY3Rzd2F0Y2hlcy5jb20ifSx7InR5cGUiOiJkbnMiLCJ2YWx1ZSI6IioucHJvamVjdHN3YXRjaGVzLmNvbSJ9XX0", "signature": "jdrFBWYLmQETQ_fabuL-CRwPiV4Oe-yBrys-EBhb-ASOTEGybmpa-LdhF_klgAJPzPrk9Z82LyQcblVnWZUdysIPeZen1YsxkiCQWEZcfACG0HRKllCTdlVw8gH7qfW5kkuJaWTa8NLMAhUkTTM7cAwEspqbkf3yNrThT9chyB32sadcqK_BDaylPXMIHxCZ6e2cuR9Bt7vSsmS2cKJz-9dbO9ZEFZ_OV-mcwWv18fkZSUTBjlkSL7BKnXn4XXteLWw0Vb11-98fH2Q55r3q-xC2NkTGf-psLT1b1JJBsH9knUZgURPI8xXsbnu3kHwpIC03Y2vqJgkfn7vYC2znOQ"}'
[Mon Jan 14 04:52:20 UTC 2019] _postContentType='application/jose+json'
[Mon Jan 14 04:52:20 UTC 2019] Http already initialized.
[Mon Jan 14 04:52:20 UTC 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.kB7u49OI66  -g '
[Mon Jan 14 04:52:20 UTC 2019] _ret='0'
[Mon Jan 14 04:52:20 UTC 2019] original='{
  "status": "pending",
  "expires": "2019-01-21T04:52:20.355630767Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "*.mydomain.com"
    },
    {
      "type": "dns",
      "value": "mydomain.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck",
    "https://acme-v02.api.letsencrypt.org/acme/authz/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/47424010/270427679"
}'
[Mon Jan 14 04:52:20 UTC 2019] responseHeaders='HTTP/1.1 201 Created
Server: nginx
Content-Type: application/json
Content-Length: 550
Boulder-Requester: 47424010
Location: https://acme-v02.api.letsencrypt.org/acme/order/47424010/270427679
Replay-Nonce: goYW5xrrM4c0WdBIEm6Krdq6xxV7XX97nVfvAbrOuHQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 14 Jan 2019 04:52:20 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 14 Jan 2019 04:52:20 GMT
Connection: keep-alive
'
[Mon Jan 14 04:52:20 UTC 2019] response='{"status":"pending","expires":"2019-01-21T04:52:20.355630767Z","identifiers":[{"type":"dns","value":"*.mydomain.com"},{"type":"dns","value":"mydomain.com"}],"authorizations":["https://acme-v02.api.letsencrypt.org/acme/authz/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck","https://acme-v02.api.letsencrypt.org/acme/authz/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw"],"finalize":"https://acme-v02.api.letsencrypt.org/acme/finalize/47424010/270427679"}'
[Mon Jan 14 04:52:20 UTC 2019] code='201'
[Mon Jan 14 04:52:20 UTC 2019] Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/47424010/270427679'
[Mon Jan 14 04:52:20 UTC 2019] _authorizations_seg='https://acme-v02.api.letsencrypt.org/acme/authz/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck,https://acme-v02.api.letsencrypt.org/acme/authz/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw'
[Mon Jan 14 04:52:20 UTC 2019] _authz_url='https://acme-v02.api.letsencrypt.org/acme/authz/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck'
[Mon Jan 14 04:52:20 UTC 2019] url='https://acme-v02.api.letsencrypt.org/acme/authz/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck'
[Mon Jan 14 04:52:20 UTC 2019] payload
[Mon Jan 14 04:52:20 UTC 2019] Use cached jwk for file: /root/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
[Mon Jan 14 04:52:20 UTC 2019] Use _CACHED_NONCE='goYW5xrrM4c0WdBIEm6Krdq6xxV7XX97nVfvAbrOuHQ'
[Mon Jan 14 04:52:20 UTC 2019] nonce='goYW5xrrM4c0WdBIEm6Krdq6xxV7XX97nVfvAbrOuHQ'
[Mon Jan 14 04:52:20 UTC 2019] POST
[Mon Jan 14 04:52:20 UTC 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck'
[Mon Jan 14 04:52:20 UTC 2019] body='{"protected": "eyJub25jZSI6ICJnb1lXNXhyck00YzBXZEJJRW02S3JkcTZ4eFY3WFg5N25WZnZBYnJPdUhRIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei9uVkRJd0RSMmVFbDBPM3NvM3NzOEFaTEx0RmNuYXZaR2dnVHBhSHJ1QWNrIiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC80NzQyNDAxMCJ9", "payload": "", "signature": "sAUl8b0bG0uVkuN3CoHFVjVr5jLRmvNyVM3IldffWxGen2M8tl7-PEMMSSozvHYNyl0vDDp-r0KIvERMVSscjyYRsi9EWzd_tf8DE86B5cnWFPIwHRMaddPX97Gmdm0JLwZsW6MrTTm7iT2mvCI_0glfUFMWt_ir9NIB02Zs3IBd8zf8P2hk1PbvOOCjAnovDIFolTpo5rbPj4gD4ITfCunRavlM_mHgxMnvJV8u85JCkuneEmv-IjVU8CK8pxVFiTYNWYPv4zDl8sdObxumWJQwFN-5uV4cuhXaEnl9JLsgyk_I7gjRZqabit34VBKIQzEmIxOPVY9NT3_z_Bvdtw"}'
[Mon Jan 14 04:52:20 UTC 2019] _postContentType='application/jose+json'
[Mon Jan 14 04:52:20 UTC 2019] Http already initialized.
[Mon Jan 14 04:52:20 UTC 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.kB7u49OI66  -g '
[Mon Jan 14 04:52:20 UTC 2019] _ret='0'
[Mon Jan 14 04:52:20 UTC 2019] original='{
  "identifier": {
    "type": "dns",
    "value": "mydomain.com"
  },
  "status": "pending",
  "expires": "2019-01-21T04:52:20Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267",
      "token": "jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs"
    }
  ],
  "wildcard": true
}'
[Mon Jan 14 04:52:20 UTC 2019] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 430
Boulder-Requester: 47424010
Replay-Nonce: GwWyTbu74ivQi1-3VSj8Zo36be_VKpUSBoud5LfqWCo
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 14 Jan 2019 04:52:20 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 14 Jan 2019 04:52:20 GMT
Connection: keep-alive
'
[Mon Jan 14 04:52:20 UTC 2019] response='{"identifier":{"type":"dns","value":"mydomain.com"},"status":"pending","expires":"2019-01-21T04:52:20Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267","token":"jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs"}],"wildcard": true}'
[Mon Jan 14 04:52:20 UTC 2019] code='200'
[Mon Jan 14 04:52:20 UTC 2019] response='{"identifier":{"type":"dns","value":"mydomain.com"},"status":"pending","expires":"2019-01-21T04:52:20Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267","token":"jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs"}],"wildcard": true}'
[Mon Jan 14 04:52:20 UTC 2019] _d='*.mydomain.com'
[Mon Jan 14 04:52:20 UTC 2019] _authz_url='https://acme-v02.api.letsencrypt.org/acme/authz/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw'
[Mon Jan 14 04:52:20 UTC 2019] url='https://acme-v02.api.letsencrypt.org/acme/authz/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw'
[Mon Jan 14 04:52:20 UTC 2019] payload
[Mon Jan 14 04:52:20 UTC 2019] Use cached jwk for file: /root/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
[Mon Jan 14 04:52:20 UTC 2019] Use _CACHED_NONCE='GwWyTbu74ivQi1-3VSj8Zo36be_VKpUSBoud5LfqWCo'
[Mon Jan 14 04:52:20 UTC 2019] nonce='GwWyTbu74ivQi1-3VSj8Zo36be_VKpUSBoud5LfqWCo'
[Mon Jan 14 04:52:20 UTC 2019] POST
[Mon Jan 14 04:52:20 UTC 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/authz/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw'
[Mon Jan 14 04:52:20 UTC 2019] body='{"protected": "eyJub25jZSI6ICJHd1d5VGJ1NzRpdlFpMS0zVlNqOFpvMzZiZV9WS3BVU0JvdWQ1TGZxV0NvIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei9QWXcxUVpEQ3Y0Vm1lOWU2NEZON05yekZteF9SVzIxUHJkc0dMUUJhdnV3IiwgImFsZyI6ICJSUzI1NiIsICJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC80NzQyNDAxMCJ9", "payload": "", "signature": "dUt7KOUbDjajWjvz86HCZnrryrrbCe7o13hLsykIJuyr_93cLnDRl3LyH-envNa3qQKlqeUdpwUksVWUdhuJL1oIe6DZq6bgZjS8C-Sf8YjQ2mTIhHV8EKEGnTh1cxdY83QY0V48N4vHQ12l2M-hd1Z_2ENcln4UnTcAt9QFhWkMaIF_FLoMjlXJf-G_6HgiOPwvrBFa5rVT-PUfHIf5TlVx8KO2T6S82wit6kS_DTeWYDwlXEGyAQYb3OdE9X9MDFyfV7t4WTkbg_jhyGbr_p3RAV7-w6UJbvyZ1Izo-c5EnVkt78e5BnSAScV7ZRnQ2GHl1yM-D_hJBvM9RBJRtQ"}'
[Mon Jan 14 04:52:20 UTC 2019] _postContentType='application/jose+json'
[Mon Jan 14 04:52:20 UTC 2019] Http already initialized.
[Mon Jan 14 04:52:20 UTC 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.kB7u49OI66  -g '
[Mon Jan 14 04:52:20 UTC 2019] _ret='0'
[Mon Jan 14 04:52:20 UTC 2019] original='{
  "identifier": {
    "type": "dns",
    "value": "mydomain.com"
  },
  "status": "pending",
  "expires": "2019-01-21T04:52:20Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499268",
      "token": "MAjRBkHevFyBnbq3PZZSJkkOXmlKzwrhvJyR9RA_bdM"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269",
      "token": "8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499270",
      "token": "GPp_27RFcN5m6WwlT8uIxQGsnCUTBc9WMzU3KzKLTkI"
    }
  ]
}'
[Mon Jan 14 04:52:20 UTC 2019] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 914
Boulder-Requester: 47424010
Replay-Nonce: i4vR9mVIVRIuOfrmW4MN3pFQhAfefhPNCK7Dy_AA2w0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 14 Jan 2019 04:52:20 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 14 Jan 2019 04:52:20 GMT
Connection: keep-alive
'
[Mon Jan 14 04:52:20 UTC 2019] response='{"identifier":{"type":"dns","value":"mydomain.com"},"status":"pending","expires":"2019-01-21T04:52:20Z","challenges":[{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499268","token":"MAjRBkHevFyBnbq3PZZSJkkOXmlKzwrhvJyR9RA_bdM"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269","token":"8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic"},{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499270","token":"GPp_27RFcN5m6WwlT8uIxQGsnCUTBc9WMzU3KzKLTkI"}]}'
[Mon Jan 14 04:52:20 UTC 2019] code='200'
[Mon Jan 14 04:52:21 UTC 2019] response='{"identifier":{"type":"dns","value":"mydomain.com"},"status":"pending","expires":"2019-01-21T04:52:20Z","challenges":[{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499268","token":"MAjRBkHevFyBnbq3PZZSJkkOXmlKzwrhvJyR9RA_bdM"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269","token":"8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic"},{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499270","token":"GPp_27RFcN5m6WwlT8uIxQGsnCUTBc9WMzU3KzKLTkI"}]}'
[Mon Jan 14 04:52:21 UTC 2019] _d='mydomain.com'
[Mon Jan 14 04:52:21 UTC 2019] _authorizations_map='mydomain.com,{"identifier":{"type":"dns","value":"mydomain.com"},"status":"pending","expires":"2019-01-21T04:52:20Z","challenges":[{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499268","token":"MAjRBkHevFyBnbq3PZZSJkkOXmlKzwrhvJyR9RA_bdM"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269","token":"8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic"},{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499270","token":"GPp_27RFcN5m6WwlT8uIxQGsnCUTBc9WMzU3KzKLTkI"}]}
*.mydomain.com,{"identifier":{"type":"dns","value":"mydomain.com"},"status":"pending","expires":"2019-01-21T04:52:20Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267","token":"jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs"}],"wildcard": true}
'
[Mon Jan 14 04:52:21 UTC 2019] d='mydomain.com'
[Mon Jan 14 04:52:21 UTC 2019] Getting webroot for domain='mydomain.com'
[Mon Jan 14 04:52:21 UTC 2019] _w='dns_me'
[Mon Jan 14 04:52:21 UTC 2019] _currentRoot='dns_me'
[Mon Jan 14 04:52:21 UTC 2019] response='{"identifier":{"type":"dns","value":"mydomain.com"},"status":"pending","expires":"2019-01-21T04:52:20Z","challenges":[{"type":"http-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499268","token":"MAjRBkHevFyBnbq3PZZSJkkOXmlKzwrhvJyR9RA_bdM"},{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269","token":"8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic"},{"type":"tls-alpn-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499270","token":"GPp_27RFcN5m6WwlT8uIxQGsnCUTBc9WMzU3KzKLTkI"}]}'
[Mon Jan 14 04:52:21 UTC 2019] entry='"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269","token":"8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic"'
[Mon Jan 14 04:52:21 UTC 2019] token='8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic'
[Mon Jan 14 04:52:21 UTC 2019] uri='https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269'
[Mon Jan 14 04:52:21 UTC 2019] keyauthorization='8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g'
[Mon Jan 14 04:52:21 UTC 2019] dvlist='mydomain.com#8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g#https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269#dns-01#dns_me'
[Mon Jan 14 04:52:21 UTC 2019] d='*.mydomain.com'
[Mon Jan 14 04:52:21 UTC 2019] Getting webroot for domain='*.mydomain.com'
[Mon Jan 14 04:52:21 UTC 2019] _w='dns_me'
[Mon Jan 14 04:52:21 UTC 2019] _currentRoot='dns_me'
[Mon Jan 14 04:52:21 UTC 2019] response='{"identifier":{"type":"dns","value":"mydomain.com"},"status":"pending","expires":"2019-01-21T04:52:20Z","challenges":[{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267","token":"jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs"}],"wildcard": true}'
[Mon Jan 14 04:52:21 UTC 2019] entry='"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267","token":"jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs"'
[Mon Jan 14 04:52:21 UTC 2019] token='jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs'
[Mon Jan 14 04:52:21 UTC 2019] uri='https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267'
[Mon Jan 14 04:52:21 UTC 2019] keyauthorization='jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g'
[Mon Jan 14 04:52:21 UTC 2019] dvlist='*.mydomain.com#jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g#https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267#dns-01#dns_me'
[Mon Jan 14 04:52:21 UTC 2019] d
[Mon Jan 14 04:52:21 UTC 2019] vlist='mydomain.com#8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g#https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269#dns-01#dns_me,*.mydomain.com#jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g#https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267#dns-01#dns_me,'
[Mon Jan 14 04:52:21 UTC 2019] d='mydomain.com'
[Mon Jan 14 04:52:21 UTC 2019] _d_alias
[Mon Jan 14 04:52:21 UTC 2019] txtdomain='_acme-challenge.mydomain.com'
[Mon Jan 14 04:52:21 UTC 2019] txt='IBLM2gqQdWkjoAzcZuhFySd66fKqIJO964o1ubCco7Y'
[Mon Jan 14 04:52:21 UTC 2019] d_api='/root/.acme.sh/dnsapi/dns_me.sh'
[Mon Jan 14 04:52:21 UTC 2019] Found domain api file: /root/.acme.sh/dnsapi/dns_me.sh
[Mon Jan 14 04:52:21 UTC 2019] First detect the root zone
[Mon Jan 14 04:52:21 UTC 2019] name?domainname=mydomain.com
[Mon Jan 14 04:52:21 UTC 2019] GET
[Mon Jan 14 04:52:21 UTC 2019] url='https://api.dnsmadeeasy.com/V2.0/dns/managed/name?domainname=mydomain.com'
[Mon Jan 14 04:52:21 UTC 2019] timeout=
[Mon Jan 14 04:52:21 UTC 2019] Http already initialized.
[Mon Jan 14 04:52:21 UTC 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.kB7u49OI66  -g '
[Mon Jan 14 04:52:21 UTC 2019] ret='0'
[Mon Jan 14 04:52:21 UTC 2019] response='






<!DOCTYPE html>
<html>
<head>
	<title>Management Console</title>
	


    <meta charset="utf-8" />


	<link rel="stylesheet" href='/V2.0/css/ui.jqgrid.css;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' type="text/css" />
	<link rel="stylesheet" href='/V2.0/css/jquery.multiselect.css;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' type="text/css" />
	<link rel="stylesheet" href='/V2.0/css/jquery.multiselect.filter.css;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' type="text/css" />
	<link rel="stylesheet" href='/V2.0/css/jquery.jqplot.min.css;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' type="text/css" />
	<link rel="stylesheet" href='/V2.0/css/jquery.dataTables.css;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' type="text/css" />
	
	<link rel="stylesheet" href='/V2.0/css/console.css;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' type="text/css" />

	<link rel="stylesheet" href='/V2.0/css/dnsme.css;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' type="text/css" title="dnsme" />
	<link rel="stylesheet" href='/V2.0/css/custom-theme/jquery-ui-1.8.14.custom.css;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' type="text/css" title="dnsme" />
	<link rel="stylesheet" href='/V2.0/css/jquery.fancybox-1.3.4.css;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' type="text/css" media="screen" />
    <link rel="stylesheet" href='/V2.0/css/realtime-stats/realtime-stats-chart.css;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' type="text/css" media="screen" />

	<script type="text/javascript" src='/V2.0/js/jquery-1.6.2.min.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery-ui-1.8.16.custom.min.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.cookie.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/i18n/grid.locale-en.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.jqGrid.min.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.validate.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.populate.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.dropdownPlain.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.metadata.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.multiselect.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.multiselect.filter.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.diff.min.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.tinysort.min.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.fancybox-1.3.4.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.dataTables.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
	
	
	<script type="text/javascript" src='/V2.0/js/date.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
    <script>Date.now = function() { return +new Date; };</script>

	<script type="text/javascript" src='/V2.0/js/jquery.pagination.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>

	<script type="text/javascript" src='/V2.0/js/jquery.blockUI.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>

	<script type="text/javascript" src='/V2.0/js/highcharts.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>

    <script type="text/javascript" src='/V2.0/js/console.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>

	<script src='https://www.google.com/recaptcha/api.js'></script>

    <script>
        var require = {
            config: {
                'DataStore' : {
                    baseUrl: '/V2.0/realtimestats;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173'
                }
            }
        }
    </script>
    
<script type="text/javascript" src='/V2.0/js/realtimestats/libs/requirejs/require.js;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173' ></script>
<script>
    require.config({
        baseUrl: '/V2.0/js/realtimestats;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173'
    });
</script>








	
	<script>
		$(function() {
			$('.tabs').tabs();
			$('input:submit').button();
			$('.ui-icon').hover(
					function() { $(this).addClass('ui-state-hover'); },
					function() { $(this).removeClass('ui-state-hover'); }
				);

			$('html').ajaxError(function(event, jqXHR, ajaxSettings, error) {
				if (jqXHR.status == 500) {
					window.location.reload();
				}
				if (jqXHR.status == 403) {
					window.location.href = LOGIN_URL;
				}
				if (jqXHR.status == 415) {
					window.location.reload();
				}
				if (jqXHR.status == 405) {
					window.location.reload();
				}

			});			
			
		});
	</script>
	
</head>
<body style="background: #FFF">





<div id="submitTicket" title="Submit a support ticket" style="margins: 0 auto;">
	<p>
		Enter a title and description of your issue and a support ticket will be created for you.
	</p>
	<div id="submitTicketErrors"></div>

	<form id="submitTicketForm" autocomplete="off" >
		<fieldset class="aligned">
			<label for="ticketSubject"><span class="required" style="margin: 0 .25em; vertical-align: top" title="Required field">*</span>Subject</label>
			<input type="text" name="subject" id="ticketSubject" class="{validate:{required:true, messages:{required:'Subject is required'}}}" /><br />
			<label for="ticketContent"><span class="required" style="margin: 0 .25em; vertical-align: top" title="Required field">*</span>Issue Description</label>
			<textarea rows="10" cols="68" style="width: auto" name="contents" id="ticketContent" class="{validate:{required:true, messages:{required:'Issue Description is required'}}}"></textarea>
		</fieldset>
	</form>
	<p>
		To view the status of an existing ticket, visit the <a style="text-decoration: underline" href="https://support.dnsmadeeasy.com">support site</a>.
	</p>
</div>

<script>

	function showSubmitTicket() {
		$('#submitTicket').dialog('open');
	}
	
	ajaxForm('/V2.0/support;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173', 'POST', '#submitTicketForm', '#submitTicketErrors', function(data, responseText, jqXHR) {
		
		$('#dialog').dialog("destroy");
		$("#dialog")
			.html(
				'Your support request was successfully submitted.  You should receive a confirmation email regarding this request.  For reference, your ticket ID for this issue is:<p style="text-align: center"> ' + data.responseText + '</p>'
			)
			.dialog(
				{
					width : 350,
					modal : true,
					resizable : false,
					title : 'Success',
					buttons : {
						Ok : function() {
							$('#dialog').dialog("close");
						}
					},
					close: function() {
						$('#submitTicketForm').populate({}, {resetForm:true});
					}
				});

	}, '#submitTicket', {
		width: 600,
		block: true
	});	
	
</script>
<div style="width: 400px;margin: 0 auto;position: relative;top: 200px; text-align: center">
	<a href="/console">
		<img src="/V2.0/img/logo_dns.png;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173"/>
	</a>
	<h3>A system error has occurred.</h3>
	<p style="margin: 3em auto">
		Have no fear - our team of emergency response nerds have already been alerted and are on the case.
	</p> 

	<a href="/V2.0/;jsessionid=1FEDFF1BEF2DE9E6C0C7EF78620A0173">Return to console</a>	<br class="clear"/>
	
		<a id="submitTicketLink" onclick="showSubmitTicket();" >Submit a support ticket</a>
	
	<a target="_blank" href="https://support.dnsmadeeasy.com">Support Center</a>
	<br class="clear"/>
	<div style="margin-top: 2em">
		<small>Current IP address:   <br />
		Last logged in on Sat Jan 12 00:00:00 UTC 2019 from 45.248.59.126</small><br />
	</div>
	<div style="margin-top: 2em">
		<small>Current Date and Time: 2019-01-14 04:52:21:543</small><br />
	</div>
	
</div>

</body>
</html>'
[Mon Jan 14 04:52:21 UTC 2019] name?domainname=com
[Mon Jan 14 04:52:21 UTC 2019] GET
[Mon Jan 14 04:52:21 UTC 2019] url='https://api.dnsmadeeasy.com/V2.0/dns/managed/name?domainname=com'
[Mon Jan 14 04:52:21 UTC 2019] timeout=
[Mon Jan 14 04:52:21 UTC 2019] Http already initialized.
[Mon Jan 14 04:52:21 UTC 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.kB7u49OI66  -g '
[Mon Jan 14 04:52:21 UTC 2019] ret='0'
[Mon Jan 14 04:52:21 UTC 2019] response='






<!DOCTYPE html>
<html>
<head>
	<title>Management Console</title>
	


    <meta charset="utf-8" />


	<link rel="stylesheet" href='/V2.0/css/ui.jqgrid.css;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' type="text/css" />
	<link rel="stylesheet" href='/V2.0/css/jquery.multiselect.css;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' type="text/css" />
	<link rel="stylesheet" href='/V2.0/css/jquery.multiselect.filter.css;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' type="text/css" />
	<link rel="stylesheet" href='/V2.0/css/jquery.jqplot.min.css;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' type="text/css" />
	<link rel="stylesheet" href='/V2.0/css/jquery.dataTables.css;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' type="text/css" />
	
	<link rel="stylesheet" href='/V2.0/css/console.css;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' type="text/css" />

	<link rel="stylesheet" href='/V2.0/css/dnsme.css;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' type="text/css" title="dnsme" />
	<link rel="stylesheet" href='/V2.0/css/custom-theme/jquery-ui-1.8.14.custom.css;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' type="text/css" title="dnsme" />
	<link rel="stylesheet" href='/V2.0/css/jquery.fancybox-1.3.4.css;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' type="text/css" media="screen" />
    <link rel="stylesheet" href='/V2.0/css/realtime-stats/realtime-stats-chart.css;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' type="text/css" media="screen" />

	<script type="text/javascript" src='/V2.0/js/jquery-1.6.2.min.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery-ui-1.8.16.custom.min.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.cookie.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/i18n/grid.locale-en.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.jqGrid.min.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.validate.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.populate.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.dropdownPlain.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.metadata.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.multiselect.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.multiselect.filter.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.diff.min.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.tinysort.min.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.fancybox-1.3.4.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	<script type="text/javascript" src='/V2.0/js/jquery.dataTables.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
	
	
	<script type="text/javascript" src='/V2.0/js/date.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
    <script>Date.now = function() { return +new Date; };</script>

	<script type="text/javascript" src='/V2.0/js/jquery.pagination.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>

	<script type="text/javascript" src='/V2.0/js/jquery.blockUI.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>

	<script type="text/javascript" src='/V2.0/js/highcharts.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>

    <script type="text/javascript" src='/V2.0/js/console.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>

	<script src='https://www.google.com/recaptcha/api.js'></script>

    <script>
        var require = {
            config: {
                'DataStore' : {
                    baseUrl: '/V2.0/realtimestats;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC'
                }
            }
        }
    </script>
    
<script type="text/javascript" src='/V2.0/js/realtimestats/libs/requirejs/require.js;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC' ></script>
<script>
    require.config({
        baseUrl: '/V2.0/js/realtimestats;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC'
    });
</script>








	
	<script>
		$(function() {
			$('.tabs').tabs();
			$('input:submit').button();
			$('.ui-icon').hover(
					function() { $(this).addClass('ui-state-hover'); },
					function() { $(this).removeClass('ui-state-hover'); }
				);

			$('html').ajaxError(function(event, jqXHR, ajaxSettings, error) {
				if (jqXHR.status == 500) {
					window.location.reload();
				}
				if (jqXHR.status == 403) {
					window.location.href = LOGIN_URL;
				}
				if (jqXHR.status == 415) {
					window.location.reload();
				}
				if (jqXHR.status == 405) {
					window.location.reload();
				}

			});			
			
		});
	</script>
	
</head>
<body style="background: #FFF">





<div id="submitTicket" title="Submit a support ticket" style="margins: 0 auto;">
	<p>
		Enter a title and description of your issue and a support ticket will be created for you.
	</p>
	<div id="submitTicketErrors"></div>

	<form id="submitTicketForm" autocomplete="off" >
		<fieldset class="aligned">
			<label for="ticketSubject"><span class="required" style="margin: 0 .25em; vertical-align: top" title="Required field">*</span>Subject</label>
			<input type="text" name="subject" id="ticketSubject" class="{validate:{required:true, messages:{required:'Subject is required'}}}" /><br />
			<label for="ticketContent"><span class="required" style="margin: 0 .25em; vertical-align: top" title="Required field">*</span>Issue Description</label>
			<textarea rows="10" cols="68" style="width: auto" name="contents" id="ticketContent" class="{validate:{required:true, messages:{required:'Issue Description is required'}}}"></textarea>
		</fieldset>
	</form>
	<p>
		To view the status of an existing ticket, visit the <a style="text-decoration: underline" href="https://support.dnsmadeeasy.com">support site</a>.
	</p>
</div>

<script>

	function showSubmitTicket() {
		$('#submitTicket').dialog('open');
	}
	
	ajaxForm('/V2.0/support;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC', 'POST', '#submitTicketForm', '#submitTicketErrors', function(data, responseText, jqXHR) {
		
		$('#dialog').dialog("destroy");
		$("#dialog")
			.html(
				'Your support request was successfully submitted.  You should receive a confirmation email regarding this request.  For reference, your ticket ID for this issue is:<p style="text-align: center"> ' + data.responseText + '</p>'
			)
			.dialog(
				{
					width : 350,
					modal : true,
					resizable : false,
					title : 'Success',
					buttons : {
						Ok : function() {
							$('#dialog').dialog("close");
						}
					},
					close: function() {
						$('#submitTicketForm').populate({}, {resetForm:true});
					}
				});

	}, '#submitTicket', {
		width: 600,
		block: true
	});	
	
</script>
<div style="width: 400px;margin: 0 auto;position: relative;top: 200px; text-align: center">
	<a href="/console">
		<img src="/V2.0/img/logo_dns.png;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC"/>
	</a>
	<h3>A system error has occurred.</h3>
	<p style="margin: 3em auto">
		Have no fear - our team of emergency response nerds have already been alerted and are on the case.
	</p> 

	<a href="/V2.0/;jsessionid=E755B7A159FD4375C2ECB4A3523C65DC">Return to console</a>	<br class="clear"/>
	
		<a id="submitTicketLink" onclick="showSubmitTicket();" >Submit a support ticket</a>
	
	<a target="_blank" href="https://support.dnsmadeeasy.com">Support Center</a>
	<br class="clear"/>
	<div style="margin-top: 2em">
		<small>Current IP address:   <br />
		Last logged in on Sat Jan 12 00:00:00 UTC 2019 from 45.248.59.126</small><br />
	</div>
	<div style="margin-top: 2em">
		<small>Current Date and Time: 2019-01-14 04:52:21:963</small><br />
	</div>
	
</div>

</body>
</html>'
[Mon Jan 14 04:52:22 UTC 2019] invalid domain
[Mon Jan 14 04:52:22 UTC 2019] Error add txt for domain:_acme-challenge.mydomain.com
[Mon Jan 14 04:52:22 UTC 2019] pid
[Mon Jan 14 04:52:22 UTC 2019] No need to restore nginx, skip.
[Mon Jan 14 04:52:22 UTC 2019] _clearupdns
[Mon Jan 14 04:52:22 UTC 2019] skip dns.
[Mon Jan 14 04:52:22 UTC 2019] _on_issue_err
[Mon Jan 14 04:52:22 UTC 2019] Please check log file for more details: /root/.acme.sh/acme.sh.log
[Mon Jan 14 04:52:22 UTC 2019] _chk_vlist='mydomain.com#8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g#https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269#dns-01#dns_me,*.mydomain.com#jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g#https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267#dns-01#dns_me,'
[Mon Jan 14 04:52:22 UTC 2019] start to deactivate authz
[Mon Jan 14 04:52:22 UTC 2019] Trigger domain validation.
[Mon Jan 14 04:52:22 UTC 2019] _t_url='https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269'
[Mon Jan 14 04:52:22 UTC 2019] _t_key_authz='8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g'
[Mon Jan 14 04:52:22 UTC 2019] _t_vtype
[Mon Jan 14 04:52:22 UTC 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269'
[Mon Jan 14 04:52:22 UTC 2019] payload='{"keyAuthorization": "8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g"}'
[Mon Jan 14 04:52:22 UTC 2019] Use cached jwk for file: /root/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
[Mon Jan 14 04:52:22 UTC 2019] Use _CACHED_NONCE='i4vR9mVIVRIuOfrmW4MN3pFQhAfefhPNCK7Dy_AA2w0'
[Mon Jan 14 04:52:22 UTC 2019] nonce='i4vR9mVIVRIuOfrmW4MN3pFQhAfefhPNCK7Dy_AA2w0'
[Mon Jan 14 04:52:22 UTC 2019] POST
[Mon Jan 14 04:52:22 UTC 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269'
[Mon Jan 14 04:52:22 UTC 2019] body='{"protected": "eyJub25jZSI6ICJpNHZSOW1WSVZSSXVPZnJtVzRNTjNwRlFoQWZlZmhQTkNLN0R5X0FBMncwIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbGVuZ2UvUFl3MVFaREN2NFZtZTllNjRGTjdOcnpGbXhfUlcyMVByZHNHTFFCYXZ1dy8xMTQ0MjQ5OTI2OSIsICJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNDc0MjQwMTAifQ", "payload": "eyJrZXlBdXRob3JpemF0aW9uIjogIjhMOVBIOEU0SG5XY1BySmZfdTUzV2ZHV1pvc25xWVZxc3NKYTg1a2FpaWMuMndiNC1MX3JGb1VyQV9Pb2Q2QThrRzJlNTJzWGY1MW5NMGlQNFdjS2tfZyJ9", "signature": "x2y87z_KUgjPZaRfTErk1LrMyeIFFowskIgC8FEywWtaM_aLJGkbsBSzTXqZSVLRD4sXs-E60Of0ZwnWeiCrc92mtl-MaxJqCZ0nhcbQRdg_NA4dPrOwAY5-Odj0j9iWvKnmuK22x0C51ULhdezBWoFKEXlXyvdBJzOdlnVSmW5JThMULvZYRSTatU574qAEnY_WkK6lCIIIVEOy4PwfZhXoCGk9aeV133mqtSw7qjjPPtXzDVd6AzWuOnkvNY9f3M0GYNhJMjwKuciirkKZC60Kw4Ud6h29qMja4EXIdVA7E0TnAzMbOXm_mtZVtAlrfjj6YQ2l0ODKuthW915jjA"}'
[Mon Jan 14 04:52:22 UTC 2019] _postContentType='application/jose+json'
[Mon Jan 14 04:52:22 UTC 2019] Http already initialized.
[Mon Jan 14 04:52:22 UTC 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.kB7u49OI66  -g '
[Mon Jan 14 04:52:22 UTC 2019] _ret='0'
[Mon Jan 14 04:52:22 UTC 2019] original='{
  "type": "dns-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269",
  "token": "8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic"
}'
[Mon Jan 14 04:52:22 UTC 2019] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 223
Boulder-Requester: 47424010
Link: <https://acme-v02.api.letsencrypt.org/acme/authz/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269
Replay-Nonce: 7c8khLczjoqIEtfuyvun1JGmCvt_wK7LCHyraOFphEY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 14 Jan 2019 04:52:22 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 14 Jan 2019 04:52:22 GMT
Connection: keep-alive
'
[Mon Jan 14 04:52:22 UTC 2019] response='{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/PYw1QZDCv4Vme9e64FN7NrzFmx_RW21PrdsGLQBavuw/11442499269","token":"8L9PH8E4HnWcPrJf_u53WfGWZosnqYVqssJa85kaiic"}'
[Mon Jan 14 04:52:22 UTC 2019] code='200'
[Mon Jan 14 04:52:22 UTC 2019] Trigger domain validation.
[Mon Jan 14 04:52:22 UTC 2019] _t_url='https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267'
[Mon Jan 14 04:52:22 UTC 2019] _t_key_authz='jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g'
[Mon Jan 14 04:52:22 UTC 2019] _t_vtype
[Mon Jan 14 04:52:22 UTC 2019] url='https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267'
[Mon Jan 14 04:52:22 UTC 2019] payload='{"keyAuthorization": "jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs.2wb4-L_rFoUrA_Ood6A8kG2e52sXf51nM0iP4WcKk_g"}'
[Mon Jan 14 04:52:22 UTC 2019] Use cached jwk for file: /root/.acme.sh/ca/acme-v02.api.letsencrypt.org/account.key
[Mon Jan 14 04:52:22 UTC 2019] Use _CACHED_NONCE='7c8khLczjoqIEtfuyvun1JGmCvt_wK7LCHyraOFphEY'
[Mon Jan 14 04:52:22 UTC 2019] nonce='7c8khLczjoqIEtfuyvun1JGmCvt_wK7LCHyraOFphEY'
[Mon Jan 14 04:52:22 UTC 2019] POST
[Mon Jan 14 04:52:22 UTC 2019] _post_url='https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267'
[Mon Jan 14 04:52:22 UTC 2019] body='{"protected": "eyJub25jZSI6ICI3YzhraExjempvcUlFdGZ1eXZ1bjFKR21DdnRfd0s3TENIeXJhT0ZwaEVZIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9jaGFsbGVuZ2UvblZESXdEUjJlRWwwTzNzbzNzczhBWkxMdEZjbmF2WkdnZ1RwYUhydUFjay8xMTQ0MjQ5OTI2NyIsICJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvNDc0MjQwMTAifQ", "payload": "eyJrZXlBdXRob3JpemF0aW9uIjogImpqQmxxdUNsMEhQZUdndFBqNWI5d01RTzhMMnBuS0VkUTFUVFdBLWNiWnMuMndiNC1MX3JGb1VyQV9Pb2Q2QThrRzJlNTJzWGY1MW5NMGlQNFdjS2tfZyJ9", "signature": "XSI9bp4SFTcwo9FNDxCN2wMt8butb8jn-hO--RVXl3Lt3jiBis7d3J7iRJyJcI_5LqvPGCTGipBwE7ndyA5g0r1ubfkmeU48oNybYjfLT6_hzxiCo3Kp4IgW0BPdDbtt6hbNxSentBaI_RAWUiStZiZ6IlUBlK9wlrRLcpdagxL2OvhapPSsHLHWD2Q8wLiTmn8233Rrg8YfFpbycseXIk6QQRip1l4wctIF_AXD_wqzqEC8N_thLTI77o5fqYDqgWCCvBFRpfNfxMQSM1V9e-5t1N-6FA9znHyKMFCPJ0QP1LxgLJIYKtuM27LMCNSkXOXfBiNcPWIgYlDX1jtkug"}'
[Mon Jan 14 04:52:22 UTC 2019] _postContentType='application/jose+json'
[Mon Jan 14 04:52:22 UTC 2019] Http already initialized.
[Mon Jan 14 04:52:22 UTC 2019] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  --trace-ascii /tmp/tmp.kB7u49OI66  -g '
[Mon Jan 14 04:52:22 UTC 2019] _ret='0'
[Mon Jan 14 04:52:22 UTC 2019] original='{
  "type": "dns-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267",
  "token": "jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs"
}'
[Mon Jan 14 04:52:22 UTC 2019] responseHeaders='HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 223
Boulder-Requester: 47424010
Link: <https://acme-v02.api.letsencrypt.org/acme/authz/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267
Replay-Nonce: I-K4WbqIn6JCiucKfWA-L2vgjO4GIQsAjCpywcNhSH8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 14 Jan 2019 04:52:22 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 14 Jan 2019 04:52:22 GMT
Connection: keep-alive
'
[Mon Jan 14 04:52:22 UTC 2019] response='{"type":"dns-01","status":"pending","url":"https://acme-v02.api.letsencrypt.org/acme/challenge/nVDIwDR2eEl0O3so3ss8AZLLtFcnavZGggTpaHruAck/11442499267","token":"jjBlquCl0HPeGgtPj5b9wMQO8L2pnKEdQ1TTWA-cbZs"}'
[Mon Jan 14 04:52:22 UTC 2019] code='200'
[Mon Jan 14 04:52:22 UTC 2019] Diagnosis versions: 
openssl:openssl
OpenSSL 1.1.0h  27 Mar 2018 (Library: OpenSSL 1.1.1  11 Sep 2018)
apache:
apache doesn't exists.
nginx:
nginx version: nginx/1.13.9
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
built with OpenSSL 1.1.1-dev  xx XXX xxxx
TLS SNI support enabled
configure arguments: --add-module=/usr/local/src/naxsi/naxsi_src --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-file-aio --with-threads --add-module=/usr/local/src/ngx_cache_purge --add-module=/usr/local/src/memc-nginx-module --add-module=/usr/local/src/ngx_devel_kit --add-module=/usr/local/src/headers-more-nginx-module --add-module=/usr/local/src/echo-nginx-module --add-module=/usr/local/src/ngx_http_substitutions_filter_module --add-module=/usr/local/src/redis2-nginx-module --add-module=/usr/local/src/srcache-nginx-module --add-module=/usr/local/src/set-misc-nginx-module --add-module=/usr/local/src/ngx_http_redis --add-module=/usr/local/src/ngx_brotli --add-module=/usr/local/src/ngx_http_auth_pam_module --add-module=/usr/local/src/incubator-pagespeed-ngx-latest-beta --with-openssl=/usr/local/src/openssl --with-openssl-opt=enable-tls1_3 --sbin-path=/usr/sbin/nginx
socat:
socat by Gerhard Rieger - see www.dest-unreach.org
Usage:
socat [options] <bi-address> <bi-address>
   options:
      -V     print version and feature information to stdout, and exit
      -h|-?  print a help text describing command line options and addresses
      -hh    like -h, plus a list of all common address option names
      -hhh   like -hh, plus a list of all available address option names
      -d     increase verbosity (use up to 4 times; 2 are recommended)
      -D     analyze file descriptors before loop
      -ly[facility]  log to syslog, using facility (default is daemon)
      -lf<logfile>   log to file
      -ls            log to stderr (default if no other log)
      -lm[facility]  mixed log mode (stderr during initialization, then syslog)
      -lp<progname>  set the program name used for logging
      -lu            use microseconds for logging timestamps
      -lh            add hostname to log messages
      -v     verbose data traffic, text
      -x     verbose data traffic, hexadecimal
      -b<size_t>     set data buffer size (8192)
      -s     sloppy (continue on error)
      -t<timeout>    wait seconds before closing second channel
      -T<timeout>    total inactivity timeout in seconds
      -u     unidirectional mode (left to right)
      -U     unidirectional mode (right to left)
      -g     do not check option groups
      -L <lockfile>  try to obtain lock, or fail
      -W <lockfile>  try to obtain lock, or wait
      -4     prefer IPv4 if version is not explicitly specified
      -6     prefer IPv6 if version is not explicitly specified
   bi-address:
      pipe[,<opts>]	groups=FD,FIFO
      <single-address>!!<single-address>
      <single-address>
   single-address:
      <address-head>[,<opts>]
   address-head:
      abstract-client:<filename>	groups=FD,SOCKET,RETRY,UNIX
      abstract-connect:<filename>	groups=FD,SOCKET,RETRY,UNIX
      abstract-listen:<filename>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,UNIX
      abstract-recv:<filename>	groups=FD,SOCKET,RETRY,UNIX
      abstract-recvfrom:<filename>	groups=FD,SOCKET,CHILD,RETRY,UNIX
      abstract-sendto:<filename>	groups=FD,SOCKET,RETRY,UNIX
      create:<filename>	groups=FD,REG,NAMED
      exec:<command-line>	groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      fd:<num>	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      gopen:<filename>	groups=FD,FIFO,CHR,BLK,REG,SOCKET,NAMED,OPEN,TERMIOS,UNIX
      interface:<interface>	groups=FD,SOCKET
      ip-datagram:<host>:<protocol>	groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recv:<protocol>	groups=FD,SOCKET,RANGE,IP4,IP6
      ip-recvfrom:<protocol>	groups=FD,SOCKET,CHILD,RANGE,IP4,IP6
      ip-sendto:<host>:<protocol>	groups=FD,SOCKET,IP4,IP6
      ip4-datagram:<host>:<protocol>	groups=FD,SOCKET,RANGE,IP4
      ip4-recv:<protocol>	groups=FD,SOCKET,RANGE,IP4
      ip4-recvfrom:<protocol>	groups=FD,SOCKET,CHILD,RANGE,IP4
      ip4-sendto:<host>:<protocol>	groups=FD,SOCKET,IP4
      ip6-datagram:<host>:<protocol>	groups=FD,SOCKET,RANGE,IP6
      ip6-recv:<protocol>	groups=FD,SOCKET,RANGE,IP6
      ip6-recvfrom:<protocol>	groups=FD,SOCKET,CHILD,RANGE,IP6
      ip6-sendto:<host>:<protocol>	groups=FD,SOCKET,IP6
      open:<filename>	groups=FD,FIFO,CHR,BLK,REG,NAMED,OPEN,TERMIOS
      openssl:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,OPENSSL
      openssl-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP,OPENSSL
      pipe:<filename>	groups=FD,FIFO,NAMED,OPEN
      proxy:<proxy-server>:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,HTTP
      pty	groups=FD,NAMED,TERMIOS,PTY
      sctp-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,SCTP
      sctp-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,SCTP
      sctp4-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,SCTP
      sctp4-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,SCTP
      sctp6-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP6,SCTP
      sctp6-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,SCTP
      socket-connect:<domain>:<protocol>:<remote-address>	groups=FD,SOCKET,CHILD,RETRY
      socket-datagram:<domain>:<type>:<protocol>:<remote-address>	groups=FD,SOCKET,RANGE
      socket-listen:<domain>:<protocol>:<local-address>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE
      socket-recv:<domain>:<type>:<protocol>:<local-address>	groups=FD,SOCKET,RANGE
      socket-recvfrom:<domain>:<type>:<protocol>:<local-address>	groups=FD,SOCKET,CHILD,RANGE
      socket-sendto:<domain>:<type>:<protocol>:<remote-address>	groups=FD,SOCKET
      socks4:<socks-server>:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      socks4a:<socks-server>:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP,SOCKS4
      stderr	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdin	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdio	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      stdout	groups=FD,FIFO,CHR,BLK,REG,SOCKET,TERMIOS,UNIX,IP4,IP6,UDP,TCP,SCTP
      system:<shell-command>	groups=FD,FIFO,SOCKET,EXEC,FORK,TERMIOS,PTY,PARENT,UNIX
      tcp-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,IP6,TCP
      tcp-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,IP6,TCP
      tcp4-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP4,TCP
      tcp4-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP4,TCP
      tcp6-connect:<host>:<port>	groups=FD,SOCKET,CHILD,RETRY,IP6,TCP
      tcp6-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RETRY,RANGE,IP6,TCP
      tun[:<ip-addr>/<bits>]	groups=FD,CHR,NAMED,OPEN,INTERFACE
      udp-connect:<host>:<port>	groups=FD,SOCKET,IP4,IP6,UDP
      udp-datagram:<host>:<port>	groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,IP6,UDP
      udp-recv:<port>	groups=FD,SOCKET,RANGE,IP4,IP6,UDP
      udp-recvfrom:<port>	groups=FD,SOCKET,CHILD,RANGE,IP4,IP6,UDP
      udp-sendto:<host>:<port>	groups=FD,SOCKET,IP4,IP6,UDP
      udp4-connect:<host>:<port>	groups=FD,SOCKET,IP4,UDP
      udp4-datagram:<remote-address>:<port>	groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP4,UDP
      udp4-recv:<port>	groups=FD,SOCKET,RANGE,IP4,UDP
      udp4-recvfrom:<host>:<port>	groups=FD,SOCKET,CHILD,RANGE,IP4,UDP
      udp4-sendto:<host>:<port>	groups=FD,SOCKET,IP4,UDP
      udp6-connect:<host>:<port>	groups=FD,SOCKET,IP6,UDP
      udp6-datagram:<host>:<port>	groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-listen:<port>	groups=FD,SOCKET,LISTEN,CHILD,RANGE,IP6,UDP
      udp6-recv:<port>	groups=FD,SOCKET,RANGE,IP6,UDP
      udp6-recvfrom:<port>	groups=FD,SOCKET,CHILD,RANGE,IP6,UDP
      udp6-sendto:<host>:<port>	groups=FD,SOCKET,IP6,UDP
      unix-client:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-connect:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-listen:<filename>	groups=FD,SOCKET,NAMED,LISTEN,CHILD,RETRY,UNIX
      unix-recv:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX
      unix-recvfrom:<filename>	groups=FD,SOCKET,NAMED,CHILD,RETRY,UNIX
      unix-sendto:<filename>	groups=FD,SOCKET,NAMED,RETRY,UNIX`

```
Any help highly appreciated. What could be the problem?

### PR DESCRIPTION
**Pull request by Blfrg**
Fixes #2031

Thanks to @ptoal for locating the problem and providing a clean solution.
However, since the suggested solution required a dependency on jq, this solution does not.

The original parser started pulling the first ID found in the response.
The desired ID is now at the end of the response.
This change modifies the existing regex to locate the last ID at the end of the response.

### CODE REVIEW

**Comment by ptoal** [comment]
This solution is still fragile, but I agree that it is currently an effective fix without creating a dependency on jq.  I think this is a reasonable compromise that will last until DME changes the response format again.

**Comment by Blfrg** [comment]
Agreed regarding the fragility without utilizing jq (which would be the most effective and reliable solution).
However I wasn't certain we wanted to add the dependency, or how we would mitigate when it isn't available.

File: dnsapi/dns_me.sh [hunk 1]
```diff
@@ -114,7 +114,7 @@ _get_root() {
     fi
 
     if _contains "$response" "\"name\":\"$h\""; then
-      _domain_id=$(printf "%s\n" "$response" | _egrep_o "\"id\":[^,]*" | head -n 1 | cut -d : -f 2 | tr -d '}')
+      _domain_id=$(printf "%s\n" "$response" | _egrep_o "\"id\":[0-9]+}$" | head -n 1 | cut -d : -f 2 | tr -d '}')
```
Comment (Neilpang) [inline dnsapi/dns_me.sh]: how about this one:

```
echo "response" | tr -d ' \r\n' | tr '{}' '\n' | grep "$h" | tr ',' '\n' | grep '"id":' | cut -d : -f 2
```

**Comment by Blfrg** [comment]
Thank you @Neilpang for the improved suggestion!

However I believe this method still relied on the `"id"` ending up in the same group/line as the domain `"name"` after `tr '{}' '\n'` and still assumes it would still be the last property on the line.

Going with the theory that the `"id"` could end up anywhere in the output (not just at the end)
the updated commit follows the concept that we only want the *outer most* `"id"` property of the response, regardless of where it is in the response.

The logic is as follows:
1. Trim the first bracket `{`
2. Trim the last bracket `}`
3. Trim all inner brackets `{.*}` (whole objects)
4. Locate the only remaining `"id"` and return it's value

**Comment by bradvido** [comment]
Is there a reason you're not just parsing the JSON and getting the id property?  This seems pretty frail, relying of egrep of a json string

**Comment by Blfrg** [comment]
> Is there a reason you're not just parsing the JSON and getting the id property? This seems pretty frail, relying of egrep of a json string

@bradvido The intent is to not add any dependencies that might not exist on the users machine.
`jq` is an obvious **reliable** solution (as proposed by @ptoal)

Trying to stick to standard system utilities I've found the following potential options to include:
[JSON.sh](https://github.com/dominictarr/JSON.sh)
[JSON.awk](https://github.com/step-/JSON.awk)

However I'm not certain if either of those are path's we want to go down.
That would be for @Neilpang to decide, and I believe is a broader scope than the issue/fix at hand.

**Comment by Blfrg** [comment]
> @Blfrg I needed to change line 117 back to the following for certificates to be able to renew.
> 
> `_domain_id=$(printf "%s\n" "$response" | _egrep_o "\"id\":[^,]*" | head -n 1 | cut -d : -f 2 | tr -d '}')`
> 
> I'm using this script on Pfsense 2.4.4-p3 with the acme package version 0.6.5
> 
> Screen Shot 2020-02-26 at 10 32 57 am

@Wasca see pull request #2783 stemming from issue #2767
