### PR TITLE
fix(truenas): broken script since 23.10 scale release

### LINKED ISSUE #6088: Truenas deploy doesn't works with version 24.10
Steps to reproduce
------------------
Truenas SCALE version 24.10 and use the truenas deploy script.

Debug log
-----------------
/home/admin/.acme.sh/deploy/truenas.sh: line 128: [: : integer expression expected
Unable to set WebDAV certificate
Error deploying for domain: nas.unicornafk.fr
Error encountered while deploying.

```
 ./acme.sh --issue --dns dns_pdns -d nas.unicornafk.fr --ca-bundle ../ca.crt --dnssleep 30 --insecure -d nas.unicornafk.fr --deploy --deploy-hook truenas
```

### PR DESCRIPTION
**Pull request by M0NsTeRRR**
Fix #6088 

TrueNAS scale has deprecated several built-in applications across recent versions:

- In version 23.10, **S3** and **WebDAV** were deprecated. More details can be found [here](https://www.truenas.com/docs/scale/23.10/gettingstarted/scalereleasenotes/#service-deprecations).
- In version 24.10, support for **Kubernetes Helm chart apps** was deprecated. See [release notes](https://www.truenas.com/docs/scale/24.10/gettingstarted/scalereleasenotes/#upgrade-notes) for more information.

I've also added support for new apps system (docker)

New script output
```
The domain 'nas.unicornafk.fr' seems to already have an ECC cert, let's use it.
Testing Connection TrueNAS
TrueNAS system state: "READY".
Getting TrueNAS version
Detected TrueNAS system os: SCALE
Detected TrueNAS system version: 24.10.0.2
Getting current active certificate from TrueNAS
Uploading new certificate to TrueNAS
Fetching list of installed certificates
Current activate certificate ID: 45
Checking if any app is using the same certificate as TrueNAS web UI. Tool 'jq' is required
Query all apps
Found 1 apps
Checking for each app if an update is needed
Updating certificate from 44 to 45 for app: minio
Checking if FTP certificate is the same as the TrueNAS web UI
FTP certificate is not configured or is not the same as TrueNAS web UI
Deleting old certificate
Reloading TrueNAS web UI
Success
```

### CODE REVIEW

**Comment by M0NsTeRRR** [comment]
The PR is good for review :)

File: deploy/truenas.sh [hunk 1]
```diff
@@ -64,6 +64,20 @@ truenas_deploy() {
   _response=$(_get "$_api_url/system/state")
   _info "TrueNAS system state: $_response."
 
+  _info "Getting TrueNAS version"
+  _response=$(_get "$_api_url/system/version")
+
+  if [[ "$_response" = *"SCALE"* ]]; then
```
Comment (Neilpang) [inline deploy/truenas.sh:70]: don't use `[[` and `]]`
please use `[`

Comment (M0NsTeRRR) [reply deploy/truenas.sh]: Should be better now :)
